# Generated by Django 4.2.29 on 2026-06-23 09:10

from django.db import migrations, models
import skill_assessment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SkillAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        upload_to=skill_assessment.models.skill_video_name
                    ),
                ),
                ("assessment_name", models.CharField(max_length=255)),
                ("participant_name", models.CharField(max_length=255)),
                ("test_name", models.CharField(max_length=255)),
                ("is_registered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
